Demonstrate error with multiple data sources.
Running this example causes an error at startup:

19:27:28.396 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [org.jobrunr.scheduling.JobScheduler]

Message: Multiple possible bean candidates found: [javax.sql.DataSource, javax.sql.DataSource]
Path Taken: new RecurringMethodProcessor([JobScheduler jobScheduler]) --> JobScheduler.jobScheduler([StorageProvider storageProvider])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [org.jobrunr.scheduling.JobScheduler]

Message: Multiple possible bean candidates found: [javax.sql.DataSource, javax.sql.DataSource]
Path Taken: new RecurringMethodProcessor([JobScheduler jobScheduler]) --> JobScheduler.jobScheduler([StorageProvider storageProvider])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2363)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1933)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1189)
	at org.jobrunr.micronaut.autoconfigure.$JobRunrFactory$JobScheduler0$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1933)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1189)
	at org.jobrunr.micronaut.autoconfigure.$RecurringMethodProcessor$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3685)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3567)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:971)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:956)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:938)
	at io.micronaut.context.DefaultBeanContext.lambda$initializeContext$30(DefaultBeanContext.java:1985)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1984)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:237)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3453)
	at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3883)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:329)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:313)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at org.jobrunr.examples.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [javax.sql.DataSource, javax.sql.DataSource]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2429)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:455)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3253)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3140)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3054)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2750)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:888)
	at org.jobrunr.micronaut.autoconfigure.storage.JobRunrSqlStorageProviderFactory.sqlStorageProvider(JobRunrSqlStorageProviderFactory.java:30)
	at org.jobrunr.micronaut.autoconfigure.storage.$JobRunrSqlStorageProviderFactory$SqlStorageProvider0$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
	... 35 common frames omitted

This error only occurs when multiple data sources are configured
and /no default datasource/ is configured.

The cause of this error is an eager Optional...orElse in
JobRunrSqlStorageProviderFactory:

        DataSource dataSource = configuration.getDatabase().getDatasource()
                .map(datasourceName -> beanContext.getBean(DataSource.class, Qualifiers.byName(datasourceName)))
                .orElse(beanContext.getBean(DataSource.class));

The .orElse() is eagerly-evaluated. When there are multiple data
sources, none of which is the default data source,
getBean(DataSource.class) throws an exception.